model_name: enzyme_reaction_clip
chemprop_num_layers: 5
chemprop_hidden_dim: 1280
chemprop_node_dim: 9
chemprop_edge_dim: 3
chemprop_pool: null
aggregate_over_edges: false
lr: 1e-4
adam_betas: [0.9, 0.999]
weight_decay: 0.05
use_amsgrad: false
max_epochs: 30
warmup_init_lr: 1e-4
warmup_min_lr: 1e-5
warmup_start_lr: 1e-6
warmup_steps: 100.0 # Float sic clipzyme
scheduler_interval: epoch
monitor: val_loss
use_protein_structure: true
pool_type: sum
egcl_layers: 6
use_sinusoidal: true
protein_dim: ${.chemprop_hidden_dim}
dropout: 0
coor_weights_clamp_value: null
norm_coors_scale_init: 0.01
norm_coors: true
norm_feats: true
soft_edge: 0
message_dim: 24
edge_attr_dim: 0
feat_proj_dim: 1280
update_coors: true
update_feats: true
neighbour_aggr: mean

# NOTE: If provided, overrides all args passed to model.
# NOTE: use '_' instead of '=' in the filename
# Note: this is just the fn, e.g., epoch_0-step_62.ckpt
ckpt_fn: null