defaults:
  - filepaths: base
  - data: sprhea_random_rc_arc
  - model: rc_agg
  - training: base
  - _self_

hpo_seed: 1234
n_trials: 1000
timeout: 86400 # seconds
objective: val_roc
direction: maximize # maximize | minimize
data:
  split_idx: 0
study_name: "${model.name}_${data.split_strategy}_split_${data.split_idx}_obj_${.objective}"

hp_bounds:
  model:
    d_h_encoder: 
      values: [10, 1000]
      type: int_log
    encoder_depth:
      values: [1, 6]
      type: int
    model:
      values: ['linear', 'ffn']
      type: categorical
  training:
    pos_multiplier:
      values: [1, 3]
      type: int
  data:
    neg_multiple:
      values: [1, 10]
      type: int

hydra:
  run:
    dir: ${filepaths.results}/hpo
  job:
    chdir: True
    name: ${...study_name}