defaults:
  - filepaths: base
  - _self_

dataset: time_split
toc: 250915_time_split
rules: ${filepaths.artifacts}/rc_plus_0_rules.csv
additional_blacklist: reactions_seen_pre_250915.txt # Exclude predicted rxns by those in here in addition to dataset_toc

hydra:
  run:
    dir: ${filepaths.data}/${...dataset}
  job:
    chdir: True