defaults:
  - filepaths: base
  - data: sprhea_random_rc_arc
  - model: structural_clipzyme
  - training: clipzyme
  - _self_

exp: structural_clipzyme # Critical: se to structural_clipzyme when you treain next round!!
test_only: false

hydra:
  sweeper:
    params:
      data.split_idx: range(${data.n_splits})

  sweep:
    dir: ${filepaths.results}/predictions
    subdir: .
  run:
    dir: ${filepaths.results}/predictions
  job:
    chdir: True